name: antilostaccount
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #depedency injection
  get_it: ^7.1.2
  #state management
  flutter_bloc: ^7.0.0
  # Value equality
  equatable: ^2.0.0
  # Functional programming thingies
  dartz: ^0.10.1
  # Local cache
  shared_preferences: ^2.0.5
  # Intl
  intl: ^0.17.0
  #svg render
  flutter_svg: ^0.22.0
  #shimmer line
  shimmer: ^2.0.0
  #local database
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  flutter_secure_storage: ^5.0.2
  #email validator
  email_validator: ^2.0.1
  #onboard screen
  introduction_screen: ^3.0.2
  #fingerprint
  local_auth: ^2.0.0
  #color
  pigment: ^1.0.4
  #uid
  uuid: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  build_runner: ^2.1.10

flutter:

  uses-material-design: true


  assets:
    - assets/

